<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Seat & Time Report — C-Net Library</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f3f6f8;color:#172033;font:15px/1.5 Arial,sans-serif}.wrap{max-width:1280px;margin:30px auto;padding:0 18px}h1{margin:0;color:#102a43}a,button{color:#fff;background:#0f766e;border:0;border-radius:8px;padding:10px 14px;text-decoration:none;cursor:pointer;display:inline-block}header,.filters,.actions{display:flex;gap:12px;flex-wrap:wrap;align-items:center;justify-content:space-between}input,select{padding:9px;border:1px solid #bbcbd5;border-radius:6px}label{display:block;font-weight:bold}.filters,.summary{background:#fff;padding:18px;border-radius:12px;margin:18px 0}.summary{display:flex;gap:24px;flex-wrap:wrap}.campus{margin-top:24px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}.seat{background:white;border:1px solid #d9e4ea;border-radius:12px;overflow:hidden}.seat-head{padding:12px 14px;background:#102a43;color:white;display:flex;justify-content:space-between}.seat.disabled{opacity:.65}.period{display:flex;justify-content:space-between;gap:10px;padding:10px 14px;border-bottom:1px solid #e4eaef}.occupied{background:#fff2d8}.free{background:#e8f8f1;color:#0b6658}.time{white-space:nowrap;font-weight:bold}.muted{color:#64748b}.bar{height:14px;background:#e8f8f1;position:relative;margin:12px 14px}.bar span{position:absolute;height:100%;background:#f2b857}.btn-small{font-size:11px;padding:4px 8px}table{width:100%;border-collapse:collapse}th,td{text-align:left;border-bottom:1px solid #ddd;padding:8px}.print-table{display:none} @media print{body{background:white;font-size:11px}.wrap{margin:0;padding:0}.no-print,.grid{display:none}.print-table{display:table}.summary{padding:8px;margin:8px 0}.campus{break-inside:avoid}a{color:black;background:none}th{background:#eee}tr{break-inside:avoid}h1{font-size:20px}}
</style></head><body><main class="wrap">
<header><div><h1>Seat & Time Report</h1><p class="muted">{{ $date }} · All times in IST (24-hour clock) · 00:00–24:00 is a full day.</p></div><div class="actions no-print"><a href="{{ route('home') }}">Home</a>@if($admin)<a href="{{ route('admin.study-space.index') }}">Manage seats & students</a>@endif<a href="{{ request()->fullUrlWithQuery(['format'=>'csv']) }}">Download CSV</a><button onclick="window.print()">Print / Save PDF</button></div></header>
<form class="filters no-print" method="get"><div><label for="campus">Campus</label><select id="campus" name="branch_id"><option value="">All campuses</option>@foreach($branches as $b)<option value="{{ $b->id }}" @selected($branchId===$b->id)>{{ $b->name }}</option>@endforeach</select></div><div><label for="date">Report date</label><input id="date" type="date" name="date" value="{{ $date }}" required></div><button>Show report</button></form>
@if(session('success'))<p>{{ session('success') }}</p>@endif
<div class="summary"><strong>{{ count($rows) }} seats</strong><span>{{ collect($rows)->filter(fn($r)=>count($r['windows'])>0)->count() }} seats with bookings</span><span>{{ collect($rows)->filter(fn($r)=>$r['enabled'] && count($r['free'])>0)->count() }} seats with free hours</span></div>
@forelse(collect($rows)->groupBy('campus') as $campus=>$campusRows)<section class="campus"><h2>{{ $campus }}</h2><div class="grid">
@foreach($campusRows as $r)<article class="seat {{ $r['enabled']?'':'disabled' }}"><div class="seat-head"><strong>Seat {{ $r['seat'] }}</strong><span>{{ $r['hall'] }} @if(!$r['enabled']) · Disabled @endif</span></div><div class="bar" aria-hidden="true">@foreach($r['windows'] as $w)<span style="left:{{ $w['start']/14.4 }}%;width:{{ ($w['end']-$w['start'])/14.4 }}%"></span>@endforeach</div>
@foreach($r['windows'] as $w)<div class="period occupied"><span>{{ $w['name'] }}@if($admin)<form method="POST" action="{{ route('admin.seat-allocations.destroy',$w['id']) }}" onsubmit="return confirm('Remove this seat allocation? Student and payments will remain.')">@csrf @method('DELETE')<button class="btn-small">Remove allocation</button></form>@endif</span><span class="time">{{ \App\Services\DailySeatWindow::label($w['start']) }}–{{ \App\Services\DailySeatWindow::label($w['end']) }}</span></div>@endforeach
@foreach($r['free'] as [$start,$end])<div class="period free"><span>{{ $r['enabled']?'Available':'Disabled' }}</span><span class="time">{{ \App\Services\DailySeatWindow::label($start) }}–{{ \App\Services\DailySeatWindow::label($end) }}</span></div>@endforeach</article>@endforeach</div>
<table class="print-table"><thead><tr><th>Hall</th><th>Seat</th><th>Student / availability</th><th>Start (IST)</th><th>End (IST)</th></tr></thead><tbody>@foreach($campusRows as $r)@foreach($r['windows'] as $w)<tr><td>{{ $r['hall'] }}</td><td>{{ $r['seat'] }}</td><td>{{ $w['name'] }}</td><td>{{ \App\Services\DailySeatWindow::label($w['start']) }}</td><td>{{ \App\Services\DailySeatWindow::label($w['end']) }}</td></tr>@endforeach @foreach($r['free'] as [$start,$end])<tr><td>{{ $r['hall'] }}</td><td>{{ $r['seat'] }}</td><td>{{ $r['enabled']?'Available':'Disabled' }}</td><td>{{ \App\Services\DailySeatWindow::label($start) }}</td><td>{{ \App\Services\DailySeatWindow::label($end) }}</td></tr>@endforeach @endforeach</tbody></table></section>
@empty<p>No seats configured for this campus.</p>@endforelse
<p class="muted">Bookings use their actual daily hours. An overnight slot appears on both calendar dates. Fees remain valid for the purchased period; unpaid seats are released after the applicable 10th-day deadline. Availability can change before an admission is approved.</p></main>@if(request()->boolean('print'))<script>window.addEventListener('load',()=>window.print())</script>@endif</body></html>
