---
deployment:
  tasks:
    - export APPPATH=/home4/mcied45x/repositories/C-Net-Library
    - /bin/mkdir -p "$APPPATH/bootstrap/cache"
    - /bin/mkdir -p "$APPPATH/storage/app/public"
    - /bin/mkdir -p "$APPPATH/storage/framework/cache/data"
    - /bin/mkdir -p "$APPPATH/storage/framework/sessions"
    - /bin/mkdir -p "$APPPATH/storage/framework/views"
    - /bin/mkdir -p "$APPPATH/storage/logs"
    - cd "$APPPATH" && /usr/local/bin/ea-php83 artisan config:clear
    - cd "$APPPATH" && /usr/local/bin/ea-php83 artisan migrate --force
    - cd "$APPPATH" && /usr/local/bin/ea-php83 artisan db:seed --force
    - cd "$APPPATH" && /usr/local/bin/ea-php83 artisan storage:link || true
    - cd "$APPPATH" && /usr/local/bin/ea-php83 artisan optimize
