<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><link rel="icon" type="image/png" href="{{ asset('images/cnet-library-icon.png') }}">
<title>Online Admission - C-Net Library</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:#f4f7fa;color:#172033;line-height:1.55}.topbar{background:#fff;border-bottom:1px solid #e5ebf1}.nav{max-width:1120px;margin:auto;padding:16px 20px;display:flex;justify-content:space-between;align-items:center;gap:16px}.brand{font-size:22px;font-weight:900;color:#102a43;text-decoration:none}.nav a.link{color:#486581;text-decoration:none;font-weight:700}.wrap{max-width:1120px;margin:36px auto;padding:0 20px}.layout{display:grid;grid-template-columns:.8fr 1.2fr;gap:24px;align-items:start}.intro{background:linear-gradient(145deg,#0f766e,#115e59);color:#fff;border-radius:22px;padding:30px;position:sticky;top:24px}.intro h1{font-size:34px;line-height:1.15;margin:10px 0 14px}.intro p{color:#d7f3ef}.checks{margin:24px 0 0;padding:0;list-style:none}.checks li{padding:8px 0}.panel{background:#fff;border:1px solid #e3e9ef;border-radius:22px;padding:28px;box-shadow:0 14px 36px rgba(15,23,42,.06)}.panel h2{margin:0 0 6px;color:#102a43}.muted{color:#71879b}.sectionTitle{margin:26px 0 12px;font-size:14px;color:#0f766e;text-transform:uppercase;letter-spacing:.9px;font-weight:900}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.field{margin-bottom:14px}.field.full{grid-column:1/-1}label{display:block;font-size:13px;font-weight:800;color:#334e68;margin-bottom:6px}input,select,textarea{width:100%;padding:12px 13px;border:1px solid #ccd7e2;border-radius:10px;font-size:15px;background:#fff;color:#172033}input:focus,select:focus,textarea:focus{outline:2px solid #99d5cf;border-color:#0f766e}.hint{font-size:12px;color:#829ab1;margin-top:5px}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.btn{display:inline-flex;justify-content:center;align-items:center;padding:12px 18px;border-radius:10px;border:1px solid #0f766e;background:#0f766e;color:#fff;text-decoration:none;font-weight:900;cursor:pointer}.btn.alt{background:#fff;color:#0f766e}.success,.error{padding:13px 15px;border-radius:11px;margin-bottom:16px}.success{background:#f0fdf4;border:1px solid #86efac}.error{background:#fef2f2;border:1px solid #fca5a5}.note{margin-top:18px;padding:13px;border-radius:11px;background:#f8fafc;color:#64748b;font-size:13px}@media(max-width:850px){.layout{grid-template-columns:1fr}.intro{position:static}.grid{grid-template-columns:1fr}.field.full{grid-column:auto}}@media(max-width:520px){.wrap{margin:20px auto;padding:0 14px}.panel,.intro{padding:21px;border-radius:16px}.intro h1{font-size:29px}.nav{padding:14px}.nav a.link{font-size:13px}.actions .btn{width:100%}}
</style>
</head><body>
<div class="topbar"><div class="nav"><a class="brand" href="{{ route('home') }}" aria-label="C-Net Library Home"><img src="{{ asset('images/cnet-library-logo.png') }}" alt="C-Net Library" style="display:block;width:210px;max-width:48vw;height:auto"></a><a class="link" href="{{ route('home') }}">← Back to Home</a></div></div>
<div class="wrap"><div class="layout">
<aside class="intro"><div style="font-size:13px;font-weight:800;letter-spacing:1px;text-transform:uppercase">Online Admission</div><h1>Reserve your study membership online.</h1><p>Tell us your preferred branch, study slot and plan. The admin team will review the application and complete seat/membership allocation.</p><ul class="checks"><li>✓ Choose preferred branch and study slot</li><li>✓ Select an active membership plan</li><li>✓ Application reviewed by the library team</li><li>✓ Student portal can be activated after approval</li></ul></aside>
<main class="panel"><h2>Admission Application</h2><div class="muted">Fields marked as required must be completed before submission.</div>
@if(session('success'))<div class="success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="error"><strong>Please correct the following:</strong><ul style="margin-bottom:0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('admission.store') }}">@csrf
<div aria-hidden="true" style="position:absolute;left:-10000px;width:1px;height:1px;overflow:hidden"><label>Website<input type="text" name="website" value="" tabindex="-1" autocomplete="off"></label></div>
<div class="sectionTitle">Student details</div><div class="grid">
<div class="field"><label>Student Name *</label><input type="text" name="name" value="{{ old('name') }}" autocomplete="name" required></div>
<div class="field"><label>Father / Guardian Name</label><input type="text" name="father_name" value="{{ old('father_name') }}"></div>
<div class="field"><label>Mobile *</label><input type="tel" name="mobile" value="{{ old('mobile') }}" autocomplete="tel" inputmode="tel" required></div>
<div class="field"><label>Email</label><input type="email" name="email" value="{{ old('email') }}" autocomplete="email"></div>
</div>
<div class="sectionTitle">Study preference</div><div class="grid">
<div class="field"><label>Branch *</label><select name="branch_id" required><option value="">Select Branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(old('branch_id') == $branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
<div class="field"><label>Preferred Study Slot</label><select name="study_slot_id"><option value="">Select Slot</option>@foreach($studySlots as $slot)<option value="{{ $slot->id }}" @selected(old('study_slot_id') == $slot->id)>{{ $slot->name }}{{ $slot->branch?->name ? ' — '.$slot->branch->name : '' }}</option>@endforeach</select><div class="hint">Choose a slot belonging to the selected branch.</div></div>
<div class="field full"><label>Preferred Fee Plan</label><select name="fee_plan_id"><option value="">Select Fee Plan</option>@foreach($feePlans as $plan)<option value="{{ $plan->id }}" @selected(old('fee_plan_id') == $plan->id)>{{ $plan->name }} — ₹{{ number_format($plan->monthly_fee,2) }}{{ $plan->branch?->name ? ' — '.$plan->branch->name : '' }}</option>@endforeach</select><div class="hint">Only active plans valid for your selected branch can be submitted.</div></div>
</div>
<div class="sectionTitle">Address</div><div class="field"><label>Residential Address</label><textarea name="address" rows="3" autocomplete="street-address">{{ old('address') }}</textarea></div>
<div class="actions"><button class="btn" type="submit">Submit Application</button><a class="btn alt" href="{{ route('enquiry.create') }}">Not sure? Send Enquiry</a></div>
<div class="note">Submitting this form creates an admission application only. Final membership, fee and seat allocation are completed after admin review.</div>
</form></main>
</div></div></body></html>
