<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><link rel="icon" type="image/png" href="{{ asset('images/cnet-library-icon.png') }}">
<title>Online Admission - C-Net Library</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:#f4f7fa;color:#172033;line-height:1.55}.topbar{background:#fff;border-bottom:1px solid #e5ebf1}.nav{max-width:1120px;margin:auto;padding:16px 20px;display:flex;justify-content:space-between;align-items:center;gap:16px}.brand{font-size:22px;font-weight:900;color:#102a43;text-decoration:none}.nav a.link{color:#486581;text-decoration:none;font-weight:700}.wrap{max-width:1120px;margin:36px auto;padding:0 20px}.layout{display:grid;grid-template-columns:.8fr 1.2fr;gap:24px;align-items:start}.intro{background:linear-gradient(145deg,#0f766e,#115e59);color:#fff;border-radius:22px;padding:30px;position:sticky;top:24px}.intro h1{font-size:34px;line-height:1.15;margin:10px 0 14px}.intro p{color:#d7f3ef}.checks{margin:24px 0 0;padding:0;list-style:none}.checks li{padding:8px 0}.panel{background:#fff;border:1px solid #e3e9ef;border-radius:22px;padding:28px;box-shadow:0 14px 36px rgba(15,23,42,.06)}.panel h2{margin:0 0 6px;color:#102a43}.muted{color:#71879b}.sectionTitle{margin:26px 0 12px;font-size:14px;color:#0f766e;text-transform:uppercase;letter-spacing:.9px;font-weight:900}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.field{margin-bottom:14px}.field.full{grid-column:1/-1}label{display:block;font-size:13px;font-weight:800;color:#334e68;margin-bottom:6px}input,select,textarea{width:100%;padding:12px 13px;border:1px solid #ccd7e2;border-radius:10px;font-size:15px;background:#fff;color:#172033}input:focus,select:focus,textarea:focus{outline:2px solid #99d5cf;border-color:#0f766e}.hint{font-size:12px;color:#829ab1;margin-top:5px}.lockerBox,.summaryBox{grid-column:1/-1;background:#f0fdfa;border:1px solid #99d5cf;border-radius:13px;padding:15px}.lockerBox strong,.summaryBox strong{color:#0f5f59}.summaryRows{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px;font-size:13px}.summaryRows div{background:#fff;border:1px solid #d7ebe8;border-radius:9px;padding:9px}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.btn{display:inline-flex;justify-content:center;align-items:center;padding:12px 18px;border-radius:10px;border:1px solid #0f766e;background:#0f766e;color:#fff;text-decoration:none;font-weight:900;cursor:pointer}.btn.alt{background:#fff;color:#0f766e}.success,.error{padding:13px 15px;border-radius:11px;margin-bottom:16px}.success{background:#f0fdf4;border:1px solid #86efac}.error{background:#fef2f2;border:1px solid #fca5a5}.note{margin-top:18px;padding:13px;border-radius:11px;background:#f8fafc;color:#64748b;font-size:13px}@media(max-width:850px){.layout{grid-template-columns:1fr}.intro{position:static}.grid{grid-template-columns:1fr}.field.full,.lockerBox,.summaryBox{grid-column:auto}}@media(max-width:520px){.wrap{margin:20px auto;padding:0 14px}.panel,.intro{padding:21px;border-radius:16px}.intro h1{font-size:29px}.nav{padding:14px}.nav a.link{font-size:13px}.actions .btn{width:100%}.summaryRows{grid-template-columns:1fr}}
</style>
</head><body>
<div class="topbar"><div class="nav"><a class="brand" href="{{ route('home') }}"><img src="{{ asset('images/cnet-library-logo.png') }}" alt="C-Net Library" style="display:block;width:210px;max-width:48vw;height:auto"></a><a class="link" href="{{ route('home') }}">← Back to Home</a></div></div>
<div class="wrap"><div class="layout">
<aside class="intro"><div style="font-size:13px;font-weight:800;letter-spacing:1px;text-transform:uppercase">Online Admission</div><h1>Reserve your study membership online.</h1><p>Select your branch first. The form will then show only valid study slots and matching fee plans. Locker facility is optional and chargeable.</p><ul class="checks"><li>✓ Branch-wise study slots</li><li>✓ Slot-wise matching fee plans</li><li>✓ 4h / 6h / 8h / 10h / 12h / 24×7 details</li><li>✓ Optional monthly locker request</li><li>✓ Final seat allocation after admin approval</li></ul></aside>
<main class="panel"><h2>Admission Application</h2><div class="muted">Fields marked as required must be completed before submission.</div>
@if(session('success'))<div class="success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="error"><strong>Please correct the following:</strong><ul style="margin-bottom:0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('admission.store') }}" id="admissionForm">@csrf
<div aria-hidden="true" style="position:absolute;left:-10000px;width:1px;height:1px;overflow:hidden"><label>Website<input type="text" name="website" value="" tabindex="-1" autocomplete="off"></label></div>
<div class="sectionTitle">Student details</div><div class="grid">
<div class="field"><label>Student Name *</label><input type="text" name="name" value="{{ old('name') }}" required></div>
<div class="field"><label>Father / Guardian Name</label><input type="text" name="father_name" value="{{ old('father_name') }}"></div>
<div class="field"><label>Mobile *</label><input type="tel" name="mobile" value="{{ old('mobile') }}" required></div>
<div class="field"><label>Email</label><input type="email" name="email" value="{{ old('email') }}"></div>
</div>
<div class="sectionTitle">Study preference</div><div class="grid">
<div class="field"><label>Branch *</label><select name="branch_id" id="branch_id" required><option value="">Select Branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(old('branch_id') == $branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
<div class="field"><label>Preferred Study Slot</label><select name="study_slot_id" id="study_slot_id"><option value="">Select Branch First</option>@foreach($studySlots as $slot)<option value="{{ $slot->id }}" data-branch="{{ $slot->branch_id }}" data-duration="{{ $slot->is_24x7 ? '24×7' : (($slot->duration_hours ?: 'Flexible').' hr') }}" data-time="{{ $slot->is_24x7 ? '24×7' : (($slot->start_time && $slot->end_time) ? $slot->start_time.' - '.$slot->end_time : ($slot->is_flexible ? 'Flexible timing' : 'Timing as configured')) }}" @selected(old('study_slot_id') == $slot->id)>{{ $slot->name }}{{ $slot->is_24x7 ? ' · 24×7' : ($slot->duration_hours ? ' · '.$slot->duration_hours.' hr' : '') }}</option>@endforeach</select><div class="hint">Only slots for the selected branch are shown.</div></div>
<div class="field full"><label>Preferred Fee Plan</label><select name="fee_plan_id" id="fee_plan_id"><option value="">Select Study Slot First</option>@foreach($feePlans as $plan)<option value="{{ $plan->id }}" data-branch="{{ $plan->branch_id }}" data-slot="{{ $plan->study_slot_id }}" data-fee="{{ $plan->monthly_fee }}" data-validity="{{ $plan->validity_days }}" data-admission="{{ $plan->admission_fee }}" data-registration="{{ $plan->registration_fee }}" data-security="{{ $plan->security_deposit }}" @selected(old('fee_plan_id') == $plan->id)>{{ $plan->name }} — ₹{{ number_format($plan->monthly_fee,2) }} · {{ $plan->validity_days }} days</option>@endforeach</select><div class="hint">Only fee plans matching both branch and selected slot are shown.</div></div>
<div class="lockerBox"><strong>Locker Facility (Chargeable)</strong><div class="hint" style="margin-bottom:8px">Locker is optional and charged monthly at the Admin-configured rate. Locker number is allotted subject to availability.</div><label for="wants_locker">Do you want a locker?</label><select id="wants_locker" name="wants_locker" required><option value="0" @selected(old('wants_locker','0')==='0')>No, locker not required</option><option value="1" @selected(old('wants_locker')==='1')>Yes, I want a locker</option></select></div>
<div class="summaryBox"><strong>Your Selection Summary</strong><div class="summaryRows"><div><b>Branch:</b> <span id="sumBranch">Not selected</span></div><div><b>Study Slot:</b> <span id="sumSlot">Not selected</span></div><div><b>Duration/Timing:</b> <span id="sumDuration">—</span></div><div><b>Fee Plan:</b> <span id="sumPlan">Not selected</span></div><div><b>Monthly Fee:</b> <span id="sumFee">—</span></div><div><b>Validity:</b> <span id="sumValidity">—</span></div><div><b>Locker:</b> <span id="sumLocker">Not required</span></div><div><b>Additional Charges:</b> <span id="sumExtras">—</span></div></div></div>
</div>
<div class="sectionTitle">Address</div><div class="field"><label>Residential Address</label><textarea name="address" rows="3">{{ old('address') }}</textarea></div>
<div class="actions"><button class="btn" type="submit">Submit Application</button><a class="btn alt" href="{{ route('enquiry.create') }}">Not sure? Send Enquiry</a></div>
<div class="note">Submitting this form creates an application only. Final membership, seat and optional locker allocation are completed after Admin review.</div>
</form></main></div></div>
<script>
const branch=document.getElementById('branch_id'), slot=document.getElementById('study_slot_id'), plan=document.getElementById('fee_plan_id'), locker=document.getElementById('wants_locker');
const slotOptions=Array.from(slot.options).slice(1), planOptions=Array.from(plan.options).slice(1);
function filterSlots(){const b=branch.value; slotOptions.forEach(o=>{const ok=!!b&&o.dataset.branch===b;o.hidden=!ok;o.disabled=!ok;}); if(!b){slot.value='';} else if(slot.selectedOptions[0]?.disabled){slot.value='';} filterPlans();}
function filterPlans(){const b=branch.value,s=slot.value; planOptions.forEach(o=>{const ok=!!b&&!!s&&o.dataset.branch===b&&o.dataset.slot===s;o.hidden=!ok;o.disabled=!ok;}); if(!b||!s||plan.selectedOptions[0]?.disabled)plan.value=''; updateSummary();}
function money(v){const n=Number(v||0);return n?`₹${n.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`:'₹0.00';}
function updateSummary(){const bo=branch.selectedOptions[0],so=slot.selectedOptions[0],po=plan.selectedOptions[0];document.getElementById('sumBranch').textContent=branch.value?bo.textContent.trim():'Not selected';document.getElementById('sumSlot').textContent=slot.value?so.textContent.trim():'Not selected';document.getElementById('sumDuration').textContent=slot.value?`${so.dataset.duration || '—'} · ${so.dataset.time || ''}`:'—';document.getElementById('sumPlan').textContent=plan.value?po.textContent.trim():'Not selected';document.getElementById('sumFee').textContent=plan.value?money(po.dataset.fee):'—';document.getElementById('sumValidity').textContent=plan.value?`${po.dataset.validity || 0} days`:'—';document.getElementById('sumLocker').textContent=locker.value==='1'?'Requested (monthly charge applies)':'Not required';if(plan.value){const extras=[];if(Number(po.dataset.admission)>0)extras.push(`Admission ${money(po.dataset.admission)}`);if(Number(po.dataset.registration)>0)extras.push(`Registration ${money(po.dataset.registration)}`);if(Number(po.dataset.security)>0)extras.push(`Security ${money(po.dataset.security)}`);document.getElementById('sumExtras').textContent=extras.length?extras.join(' · '):'None';}else document.getElementById('sumExtras').textContent='—';}
branch.addEventListener('change',filterSlots);slot.addEventListener('change',filterPlans);plan.addEventListener('change',updateSummary);locker.addEventListener('change',updateSummary);
filterSlots(); updateSummary();
</script>
</body></html>