<!doctype html><html lang="hi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Online Admission · C-Net Library</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f7fa;color:#172d40;font:16px/1.5 Arial,sans-serif}.wrap{max-width:1100px;margin:24px auto;padding:16px}header{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-bottom:20px}header img{width:220px;max-width:55vw}.card{background:white;border:1px solid #dce5eb;border-radius:16px;padding:22px;margin-bottom:18px}h1{margin:0;font-size:27px}h2{font-size:20px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}label{font-weight:bold;display:block}input,select,textarea{width:100%;padding:12px;border:1px solid #b8c8d4;border-radius:8px;font:inherit;margin-top:5px}button,.btn{display:inline-block;background:#0f766e;color:white;padding:12px 18px;border:0;border-radius:8px;text-decoration:none;font-weight:bold;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}.note{background:#eef8f6;padding:12px;border-radius:8px}.error{background:#fff0ec;padding:12px;color:#9b2c14}.seats{display:flex;gap:9px;flex-wrap:wrap}.seats label{cursor:pointer;border:2px solid #c2d9d4;padding:10px;border-radius:8px}.seats label:has(input:checked){background:#dcfce7;border-color:#0f766e}.seats input{width:auto;margin:0 5px 0 0}table{width:100%;border-collapse:collapse;font-size:13px}td,th{padding:8px;border:1px solid #d9e2ea;text-align:left;vertical-align:top}small{color:#52697a}.scroll{overflow:auto}@media(max-width:640px){.grid{grid-template-columns:1fr}.wrap{padding:10px}.card{padding:16px}header{flex-wrap:wrap}}@media print{.no-print{display:none!important}body{background:white}.wrap{max-width:none;padding:0}.card{border:0;padding:5px;break-inside:avoid}thead{display:table-header-group}tr{break-inside:avoid}table{font-size:10px}@page{size:A4 landscape;margin:12mm}}</style></head><body><main class="wrap"><header><a href="{{ route('home') }}"><img src="{{ asset('images/cnet-library-logo.png') }}" alt="C-Net Library"></a><a href="{{ route('home') }}">होमपेज</a></header><div class="card"><h1>Admission Application</h1><p>कैंपस और पढ़ने की अवधि चुनें → उपलब्ध समय देखें → अपनी सीट चुनें → फीस देखकर आवेदन करें। अंतिम आवंटन एडमिन अप्रूवल पर होगा।</p>
@if(session('success'))<p class="note">{{ session('success') }}</p>@endif
@if(session('error'))<p class="error">{{ session('error') }}</p>@endif
@if($errors->any())<div class="error">@foreach($errors->all() as $e)<p>{{ $e }}</p>@endforeach</div>@endif
<form method="post" action="{{ route('admission.store') }}" id="application">@csrf
<input name="website" value="" tabindex="-1" autocomplete="off" aria-hidden="true" style="position:absolute;left:-9999px;width:1px">
<h2>1. कैंपस और अवधि</h2><div class="grid">
<label>कैंपस *<select name="branch_id" id="campus" required><option value="">कैंपस चुनें</option>@foreach($branches as $b)<option value="{{ $b->id }}" @selected(old('branch_id')==$b->id)>{{ $b->name }}</option>@endforeach</select></label>
<label>प्रवेश शुरू होने की तारीख *<input type="date" name="preferred_start_date" id="startDate" min="{{ today()->toDateString() }}" max="{{ today()->addYear()->toDateString() }}" value="{{ old('preferred_start_date') }}" required></label>
<label>दैनिक अवधि *<select name="study_slot_id" id="duration" required><option value="">पहले कैंपस चुनें</option>@foreach($studySlots as $s)<option value="{{ $s->id }}" data-campus="{{ $s->branch_id }}" @selected(old('study_slot_id')==$s->id)>{{ $s->is_24x7?'24×7':($s->duration_hours.' घंटे') }}</option>@endforeach</select></label>
<label>फीस प्लान *<select name="fee_plan_id" id="plan" required><option value="">पहले अवधि चुनें</option>@foreach($feePlans as $f)<option value="{{ $f->id }}" data-campus="{{ $f->branch_id }}" data-slot="{{ $f->study_slot_id }}" @selected(old('fee_plan_id')==$f->id)>{{ $f->name }} · ₹{{ $f->monthly_fee }} / {{ $f->validity_days }} दिन</option>@endforeach</select></label></div>
<h2>2. समय और खाली सीट</h2><p><small>उपलब्धता चुने हुए सदस्यता काल के लिए है। दूसरे समय में बुक सीट आपके चुने समय में खाली हो सकती है। समय अपने-आप चयनित नहीं होगा।</small></p>
<label>पढ़ने का समय *<select id="timing" required disabled><option value="">ऊपर का चयन पूरा करें</option></select></label><input type="hidden" name="preferred_start_time" id="startTime"><input type="hidden" name="preferred_end_time" id="endTime">
<p id="availabilityStatus" role="status" aria-live="polite"></p><div id="seats" class="seats"></div>
<div id="fees" class="note" hidden></div>
<h2>3. विद्यार्थी विवरण</h2><div class="grid"><label>नाम *<input name="name" value="{{ old('name') }}" required maxlength="255"></label><label>पिता / अभिभावक का नाम<input name="father_name" value="{{ old('father_name') }}" maxlength="255"></label><label>मोबाइल नंबर *<input name="mobile" type="tel" pattern="[0-9]{10}" maxlength="10" value="{{ old('mobile') }}" required autocomplete="tel"></label><label>ईमेल *<input name="email" type="email" value="{{ old('email') }}" required autocomplete="email"></label><label>Locker / लॉकर चाहिए?<select name="wants_locker"><option value="0">नहीं</option><option value="1" @selected(old('wants_locker')==1)>हाँ — मासिक शुल्क और उपलब्धता के अनुसार</option></select></label><label>पता<textarea name="address" maxlength="2000">{{ old('address') }}</textarea></label></div>
<p>सबमिट करने से सीट पक्की नहीं होती। अप्रूवल के बाद एडमिशन नंबर और लॉगिन जानकारी ईमेल पर मिलेगी।</p><button id="submitApplication" type="submit" disabled>फीस और चयन देखकर आवेदन जमा करें</button></form></div></main>
<script>
const campus=document.querySelector('#campus'),duration=document.querySelector('#duration'),plan=document.querySelector('#plan'),date=document.querySelector('#startDate'),timing=document.querySelector('#timing'),seats=document.querySelector('#seats'),status=document.querySelector('#availabilityStatus'),fees=document.querySelector('#fees'),submit=document.querySelector('#submitApplication');
const slots=[...duration.options].slice(1),plans=[...plan.options].slice(1);let windows=[],version=0,abort;
function clearAvailability(){windows=[];timing.replaceChildren(new Option('समय चुनें',''));timing.disabled=true;seats.replaceChildren();fees.hidden=true;submit.disabled=true;document.querySelector('#startTime').value='';document.querySelector('#endTime').value='';}
function filter(reset=false){
const oldDuration=reset?'':duration.value,oldPlan=reset?'':plan.value;
const campusSlots=slots.filter(o=>o.dataset.campus===campus.value);
duration.replaceChildren(new Option(!campus.value?'पहले कैंपस चुनें':campusSlots.length?'अवधि चुनें':'इस कैंपस में अवधि कॉन्फ़िगर नहीं है',''));
campusSlots.forEach(o=>duration.add(o.cloneNode(true)));duration.value=campusSlots.some(o=>o.value===oldDuration)?oldDuration:'';duration.disabled=!campusSlots.length;
const slotPlans=plans.filter(o=>o.dataset.campus===campus.value&&o.dataset.slot===duration.value);
plan.replaceChildren(new Option(!duration.value?'पहले अवधि चुनें':slotPlans.length?'फीस प्लान चुनें':'इस अवधि का फीस प्लान उपलब्ध नहीं है',''));
slotPlans.forEach(o=>plan.add(o.cloneNode(true)));plan.value=slotPlans.some(o=>o.value===oldPlan)?oldPlan:'';plan.disabled=!slotPlans.length;
load();}
async function load(){const current=++version;abort?.abort();clearAvailability();status.textContent='';if(!campus.value||!duration.value||!plan.value||!date.value)return;status.textContent='उपलब्ध समय और सीट जाँच रहे हैं…';abort=new AbortController();try{const url=new URL(@json(route('admission.availability')));url.search=new URLSearchParams({branch_id:campus.value,study_slot_id:duration.value,fee_plan_id:plan.value,start_date:date.value});const response=await fetch(url,{signal:abort.signal,headers:{Accept:'application/json'}});const data=await response.json();if(current!==version)return;if(!response.ok)throw new Error(data.message||'सीट की जानकारी नहीं मिली।');windows=data.times;windows.forEach((w,i)=>{const o=new Option(w.label+' · '+(w.available?w.available+' सीटें उपलब्ध':'सभी सीटें बुक'),String(i));o.disabled=!w.available;timing.add(o);});timing.disabled=!windows.some(w=>w.available);status.textContent=timing.disabled?'इस अवधि में कोई सीट उपलब्ध नहीं है। दूसरी अवधि या कैंपस चुनें।':'अब समय चुनें।';fees.textContent='मासिक फीस ₹'+data.monthly_fee+' · प्रवेश शुल्क ₹'+data.admission_fee+' · रजिस्ट्रेशन ₹'+data.registration_fee+' · सिक्योरिटी ₹'+data.security_deposit+' · कुल शुरुआती शुल्क ₹'+(Number(data.monthly_fee)+Number(data.admission_fee)+Number(data.registration_fee)+Number(data.security_deposit)).toFixed(2)+' · सदस्यता '+date.value+' से '+data.expiry+' तक। लॉकर का शुल्क अलग है, यदि चुना गया।';}catch(error){if(error.name!=='AbortError'&&current===version){status.textContent=error.message;}}}
campus.addEventListener('change',()=>filter(true));duration.addEventListener('change',()=>{plan.value='';filter();});plan.addEventListener('change',load);date.addEventListener('change',load);
timing.addEventListener('change',()=>{seats.replaceChildren();submit.disabled=true;fees.hidden=true;const w=windows[Number(timing.value)];if(timing.value===''||!w)return;document.querySelector('#startTime').value=w.start||'';document.querySelector('#endTime').value=w.end||'';w.seats.forEach(s=>{const label=document.createElement('label'),radio=document.createElement('input');radio.type='radio';radio.name='preferred_seat_id';radio.value=s.id;radio.required=true;radio.addEventListener('change',()=>{submit.disabled=false;fees.hidden=false;status.textContent='समय: '+w.label+' · सीट: '+s.number+' · '+s.hall;});label.append(radio,document.createTextNode('सीट '+s.number+' · '+s.hall));seats.append(label);});status.textContent='इस समय में अपनी सीट चुनें।';});filter();
</script></body></html>