<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><meta name="robots" content="noindex,nofollow,noarchive"><title>Students - C-Net Library</title>
<style>*{box-sizing:border-box}body{font-family:Arial,sans-serif;background:#f5f7fb;margin:0;color:#1f2937}.wrap{max-width:1400px;margin:26px auto;padding:0 18px}.top{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:20px}.top h1{margin:0}.muted{color:#6b7280}.nav,.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{display:inline-flex;align-items:center;justify-content:center;padding:9px 12px;border-radius:9px;border:0;text-decoration:none;background:#111827;color:#fff;font-weight:700;cursor:pointer}.btn.alt{background:#2563eb}.btn.green{background:#0f766e}.btn.red{background:#b91c1c}.btn.light{background:#e5e7eb;color:#111827}.summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:18px}.stat,.card{background:#fff;border:1px solid #e5e7eb;border-radius:14px;box-shadow:0 6px 22px rgba(15,23,42,.05)}.stat{padding:16px}.stat .k{font-size:12px;text-transform:uppercase;color:#6b7280}.stat .v{font-size:28px;font-weight:800;margin-top:6px}.card{padding:18px;margin-bottom:18px}.card h2{margin:0 0 13px}.filters{display:grid;grid-template-columns:minmax(240px,1fr) 180px auto auto;gap:10px;margin-bottom:16px}.formgrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.wide2{grid-column:span 2}.wide4{grid-column:1/-1}.field label{display:block;font-size:11px;font-weight:800;text-transform:uppercase;color:#64748b;margin-bottom:5px}input,select,textarea,button{padding:9px 11px;border:1px solid #d1d5db;border-radius:9px;font-size:14px;background:#fff;width:100%}button{background:#111827;color:#fff;font-weight:700;cursor:pointer}.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse;min-width:1040px}.table th,.table td{padding:11px;border-bottom:1px solid #edf0f4;text-align:left;font-size:13px;vertical-align:top}.table th{font-size:11px;text-transform:uppercase;color:#6b7280}.status{display:inline-block;font-size:12px;padding:5px 9px;border-radius:999px;background:#eef2ff}.status.active{background:#dcfce7;color:#166534}.status.inactive{background:#f3f4f6;color:#4b5563}.status.blocked{background:#fee2e2;color:#991b1b}.link{color:#2563eb;text-decoration:none;font-weight:700}.sub{font-size:12px;color:#6b7280;margin-top:4px}.alert{padding:12px 14px;border-radius:10px;margin-bottom:14px}.success{background:#dcfce7;color:#166534}.error{background:#fee2e2;color:#991b1b}.editbox{margin-top:9px;padding:10px;background:#f8fafc;border-radius:9px}.editgrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.editgrid input,.editgrid select{padding:7px;font-size:12px}.danger-note{font-size:11px;color:#9a3412;margin-top:5px}.pagination{margin-top:18px}@media(max-width:900px){.top{flex-direction:column}.summary{grid-template-columns:repeat(2,1fr)}.filters,.formgrid,.editgrid{grid-template-columns:1fr}.wide2,.wide4{grid-column:auto}}@media(max-width:480px){.summary{grid-template-columns:1fr}}</style>
</head><body><div class="wrap">
<div class="top"><div><h1>Student Registry</h1><div class="muted">Admin can add, edit, search, deactivate/block, and safely delete student records.</div></div><div class="nav"><a class="btn light" href="{{ route('admin.dashboard') }}">Dashboard</a><a class="btn alt" href="{{ route('admin.admissions.index') }}">Admissions</a><a class="btn alt" href="{{ route('admin.students.id-cards.bulk') }}">Bulk ID Cards</a><a class="btn" href="{{ route('admin.seats.available') }}">Available Seats</a></div></div>
@if(session('success'))<div class="alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert error"><strong>Please correct:</strong> {{ $errors->first() }}</div>@endif
<div class="summary"><div class="stat"><div class="k">Total Students</div><div class="v">{{ $summary['total'] }}</div></div><div class="stat"><div class="k">Active</div><div class="v">{{ $summary['active'] }}</div></div><div class="stat"><div class="k">Inactive</div><div class="v">{{ $summary['inactive'] }}</div></div><div class="stat"><div class="k">Blocked</div><div class="v">{{ $summary['blocked'] }}</div></div></div>
<div class="card"><h2>Add Student Directly</h2><div class="muted" style="margin-bottom:12px">Use this for walk-in/manual admission records. Membership, seat, locker and payment can then be assigned through their respective admin modules.</div><form method="POST" action="{{ route('admin.students.store') }}">@csrf<div class="formgrid">
<div class="field"><label>Branch</label><select name="branch_id" required>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(old('branch_id')==$branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
<div class="field"><label>Student ID (optional)</label><input name="student_code" value="{{ old('student_code') }}" placeholder="Auto if blank"></div>
<div class="field"><label>Name</label><input name="name" value="{{ old('name') }}" required></div><div class="field"><label>Mobile</label><input name="mobile" value="{{ old('mobile') }}" required></div>
<div class="field"><label>Father Name</label><input name="father_name" value="{{ old('father_name') }}"></div><div class="field"><label>Mother Name</label><input name="mother_name" value="{{ old('mother_name') }}"></div><div class="field"><label>DOB</label><input type="date" name="dob" value="{{ old('dob') }}"></div><div class="field"><label>Gender</label><select name="gender"><option value="">Select</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select></div>
<div class="field"><label>Email</label><input type="email" name="email" value="{{ old('email') }}"></div><div class="field"><label>Alternate Mobile</label><input name="alternate_mobile" value="{{ old('alternate_mobile') }}"></div><div class="field"><label>Guardian</label><input name="guardian_name" value="{{ old('guardian_name') }}"></div><div class="field"><label>Guardian Mobile</label><input name="guardian_mobile" value="{{ old('guardian_mobile') }}"></div>
<div class="field"><label>ID Proof Type</label><input name="id_proof_type" value="{{ old('id_proof_type') }}"></div><div class="field"><label>ID Proof No.</label><input name="id_proof_no" value="{{ old('id_proof_no') }}"></div><div class="field"><label>Joining Date</label><input type="date" name="joining_date" value="{{ old('joining_date',now()->toDateString()) }}" required></div><div class="field"><label>Status</label><select name="status"><option value="active">Active</option><option value="inactive">Inactive</option><option value="blocked">Blocked</option></select></div>
<div class="field wide4"><label>Address</label><textarea name="address" rows="2">{{ old('address') }}</textarea></div></div><div style="margin-top:12px"><button class="btn green" style="width:auto">Add Student</button></div></form></div>
<div class="card"><form method="GET" class="filters"><input type="text" name="search" value="{{ request('search') }}" placeholder="Name, mobile, email, student ID"><select name="status"><option value="">All status</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option><option value="blocked" @selected(request('status')==='blocked')>Blocked</option></select><button type="submit">Filter</button><a class="btn light" href="{{ route('admin.students.index') }}">Reset</a></form>
<div class="table-wrap"><table class="table"><thead><tr><th>Student</th><th>Contact</th><th>Branch</th><th>Membership</th><th>Seat</th><th>Status</th><th>Manage</th></tr></thead><tbody>
@forelse($students as $student) @php($membership=$student->activeMembership) @php($allocation=$student->seatAllocations->where('status','active')->sortByDesc('id')->first())
<tr><td><strong>{{ $student->name }}</strong><div class="sub">{{ $student->student_code }}</div></td><td>{{ $student->mobile }}<div class="sub">{{ $student->email ?: 'No email' }}</div></td><td>{{ $student->branch?->name ?? '—' }}</td><td>{{ $membership?->feePlan?->name ?? 'No active plan' }}@if($membership?->studySlot)<div class="sub">{{ $membership->studySlot->name }}</div>@endif</td><td>@if($allocation){{ $allocation->seat?->seat_no ?? '—' }}<div class="sub">{{ $allocation->seat?->studyHall?->name ?? '—' }}</div>@else<span class="muted">Not allocated</span>@endif</td><td><span class="status {{ $student->status }}">{{ ucfirst($student->status) }}</span></td><td><a class="link" href="{{ route('admin.students.show',$student) }}">Open Account</a>
<details class="editbox"><summary style="cursor:pointer;font-weight:700">Edit / Delete</summary><form method="POST" action="{{ route('admin.students.update',$student) }}" style="margin-top:9px">@csrf @method('PATCH')<div class="editgrid"><select name="branch_id">@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($student->branch_id==$branch->id)>{{ $branch->name }}</option>@endforeach</select><input name="student_code" value="{{ $student->student_code }}" required><input name="name" value="{{ $student->name }}" required><input name="mobile" value="{{ $student->mobile }}" required><input name="father_name" value="{{ $student->father_name }}" placeholder="Father"><input name="mother_name" value="{{ $student->mother_name }}" placeholder="Mother"><input type="date" name="dob" value="{{ $student->dob?->format('Y-m-d') }}"><select name="gender"><option value="">Gender</option><option value="male" @selected($student->gender==='male')>Male</option><option value="female" @selected($student->gender==='female')>Female</option><option value="other" @selected($student->gender==='other')>Other</option></select><input type="email" name="email" value="{{ $student->email }}" placeholder="Email"><input name="alternate_mobile" value="{{ $student->alternate_mobile }}" placeholder="Alt mobile"><input name="guardian_name" value="{{ $student->guardian_name }}" placeholder="Guardian"><input name="guardian_mobile" value="{{ $student->guardian_mobile }}" placeholder="Guardian mobile"><input name="id_proof_type" value="{{ $student->id_proof_type }}" placeholder="ID proof type"><input name="id_proof_no" value="{{ $student->id_proof_no }}" placeholder="ID proof no"><input type="date" name="joining_date" value="{{ $student->joining_date?->format('Y-m-d') }}" required><select name="status"><option value="active" @selected($student->status==='active')>Active</option><option value="inactive" @selected($student->status==='inactive')>Inactive</option><option value="blocked" @selected($student->status==='blocked')>Blocked</option></select></div><textarea name="address" rows="2" style="margin-top:7px" placeholder="Address">{{ $student->address }}</textarea><button class="btn" style="width:auto;margin-top:7px">Save Student</button></form>
<form method="POST" action="{{ route('admin.students.destroy',$student) }}" style="margin-top:8px" onsubmit="return confirm('Permanently delete {{ addslashes($student->name) }}? This is only allowed when no membership/payment/attendance/seat/book history exists.')">@csrf @method('DELETE')<button class="btn red" style="width:auto">Delete Student</button></form><div class="danger-note">If operational or financial history exists, deletion is blocked; use Inactive/Blocked instead.</div></details></td></tr>
@empty<tr><td colspan="7" class="muted" style="padding:28px;text-align:center">No students found for the selected filters.</td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $students->links() }}</div></div></div></body></html>
