<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Locker Management | C-Net Library</title>
<style>*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:#f3f6f8;color:#172033}.wrap{max-width:1400px;margin:28px auto;padding:0 18px}.top{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.btn{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:9px;padding:10px 14px;background:#102a43;color:#fff;text-decoration:none;font-weight:750;cursor:pointer}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.card{background:#fff;border:1px solid #dfe7ed;border-radius:14px;padding:18px;box-shadow:0 5px 18px rgba(15,23,42,.04);margin-bottom:18px}.value{font-size:28px;font-weight:850;color:#0f766e}.muted{color:#64748b;font-size:13px}.forms{display:grid;grid-template-columns:1fr 1fr;gap:16px}.formgrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field label{display:block;font-size:12px;font-weight:800;color:#52677a;margin-bottom:5px}.field input,.field select,.field textarea{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.full{grid-column:1/-1}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}th{color:#52677a;background:#f8fafc}.badge{display:inline-block;padding:4px 8px;border-radius:999px;background:#ecfdf5;color:#047857;font-weight:800;font-size:11px}.badge.off{background:#f1f5f9;color:#64748b}.inline{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.inline input,.inline select{padding:7px;border:1px solid #cbd5e1;border-radius:7px}.success,.error{padding:12px 14px;border-radius:10px;margin-bottom:14px}.success{background:#ecfdf5;border:1px solid #86efac}.error{background:#fef2f2;border:1px solid #fca5a5}@media(max-width:900px){.grid4,.forms{grid-template-columns:1fr 1fr}.formgrid{grid-template-columns:1fr}}@media(max-width:620px){.grid4,.forms{grid-template-columns:1fr}.top{flex-direction:column}}</style>
</head><body><div class="wrap">
<div class="top"><div><h1 style="margin:0">Locker Management</h1><div class="muted">Create lockers, set monthly charges and allocate lockers to active students.</div></div><a class="btn" href="{{ route('admin.dashboard') }}">Dashboard</a></div>
@if(session('success'))<div class="success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="error"><strong>Please correct:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid4"><div class="card"><div class="muted">Total Lockers</div><div class="value">{{ $summary['total'] }}</div></div><div class="card"><div class="muted">Active Lockers</div><div class="value">{{ $summary['active'] }}</div></div><div class="card"><div class="muted">Occupied</div><div class="value">{{ $summary['occupied'] }}</div></div><div class="card"><div class="muted">Available</div><div class="value">{{ $summary['available'] }}</div></div></div>
<div class="forms">
<div class="card"><h2 style="margin-top:0">Add Locker</h2><form method="POST" action="{{ route('admin.lockers.store') }}">@csrf<div class="formgrid"><div class="field"><label>Branch</label><select name="branch_id" required><option value="">Select branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></div><div class="field"><label>Locker No.</label><input name="locker_no" required></div><div class="field"><label>Location</label><input name="location" placeholder="Ground Floor / Hall entrance"></div><div class="field"><label>Monthly Charge (₹)</label><input type="number" step="0.01" min="0" name="monthly_charge" required></div><div class="field full"><label><input type="checkbox" name="status" value="1" checked style="width:auto"> Active</label></div></div><button class="btn" type="submit">Create Locker</button></form></div>
<div class="card"><h2 style="margin-top:0">Allocate Locker</h2><form method="POST" action="{{ route('admin.lockers.allocations.store') }}">@csrf<div class="formgrid"><div class="field"><label>Student</label><select name="student_id" required><option value="">Select student</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->student_code }} — {{ $student->name }}</option>@endforeach</select></div><div class="field"><label>Locker</label><select name="locker_id" required><option value="">Select locker</option>@foreach($lockers->where('status',true) as $locker)<option value="{{ $locker->id }}" @disabled($locker->active_allocations_count>0)>{{ $locker->branch?->name }} — {{ $locker->locker_no }} — ₹{{ number_format((float)$locker->monthly_charge,2) }}/month{{ $locker->active_allocations_count>0?' — OCCUPIED':'' }}</option>@endforeach</select></div><div class="field"><label>From</label><input type="date" name="allocated_from" value="{{ now()->toDateString() }}" required></div><div class="field"><label>To</label><input type="date" name="allocated_to"></div><div class="field"><label>Status</label><select name="status"><option value="active">Active</option><option value="reserved">Reserved</option></select></div><div class="field"><label>Remarks</label><input name="remarks"></div></div><button class="btn" type="submit">Allocate Locker</button></form></div>
</div>
<div class="card"><h2>Locker Inventory & Monthly Charge</h2><div class="tablewrap"><table><thead><tr><th>Branch</th><th>Locker</th><th>Location</th><th>Monthly Charge</th><th>Status</th><th>Update</th></tr></thead><tbody>@forelse($lockers as $locker)<tr><td>{{ $locker->branch?->name }}</td><td><strong>{{ $locker->locker_no }}</strong></td><td>{{ $locker->location ?: '—' }}</td><td>₹{{ number_format((float)$locker->monthly_charge,2) }}</td><td><span class="badge {{ $locker->status?'':'off' }}">{{ $locker->status?'Active':'Disabled' }}</span>@if($locker->active_allocations_count>0)<div class="muted">Currently occupied</div>@endif</td><td><form class="inline" method="POST" action="{{ route('admin.lockers.update',$locker) }}">@csrf @method('PATCH')<input name="locker_no" value="{{ $locker->locker_no }}" size="8" required><input name="location" value="{{ $locker->location }}" placeholder="Location" size="12"><input type="number" step="0.01" min="0" name="monthly_charge" value="{{ $locker->monthly_charge }}" style="width:95px" required><select name="status"><option value="1" @selected($locker->status)>Active</option><option value="0" @selected(!$locker->status)>Disabled</option></select><button class="btn" type="submit">Save</button></form></td></tr>@empty<tr><td colspan="6">No lockers configured yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="card"><h2>Locker Allocations</h2><div class="tablewrap"><table><thead><tr><th>Student</th><th>Locker</th><th>Period</th><th>Charge</th><th>Status / Action</th></tr></thead><tbody>@forelse($allocations as $allocation)<tr><td><strong>{{ $allocation->student?->name }}</strong><div class="muted">{{ $allocation->student?->student_code }}</div></td><td>{{ $allocation->locker?->locker_no }}<div class="muted">{{ $allocation->locker?->location }}</div></td><td>{{ $allocation->allocated_from?->format('d M Y') }} — {{ $allocation->allocated_to?->format('d M Y') ?? 'Open ended' }}</td><td>₹{{ number_format((float)$allocation->monthly_charge,2) }}/month</td><td><form class="inline" method="POST" action="{{ route('admin.lockers.allocations.update',$allocation) }}">@csrf @method('PATCH')<select name="status"><option value="reserved" @selected($allocation->status==='reserved')>Reserved</option><option value="active" @selected($allocation->status==='active')>Active</option><option value="completed" @selected($allocation->status==='completed')>Completed</option><option value="cancelled" @selected($allocation->status==='cancelled')>Cancelled</option></select><input type="date" name="allocated_to" value="{{ $allocation->allocated_to?->toDateString() }}"><input name="remarks" value="{{ $allocation->remarks }}" placeholder="Remarks"><button class="btn" type="submit">Update</button></form></td></tr>@empty<tr><td colspan="5">No locker allocations yet.</td></tr>@endforelse</tbody></table></div>{{ $allocations->links() }}</div>
</div></body></html>
