<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Hall & Seat Tools | C-Net Library</title>
<style>*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:#f3f6f8;color:#172033}.wrap{max-width:1400px;margin:24px auto;padding:0 18px}.top{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;margin-bottom:18px}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:9px;padding:10px 13px;background:#102a43;color:#fff;text-decoration:none;font-weight:750;cursor:pointer}.btn.green{background:#0f766e}.btn.red{background:#b91c1c}.btn.light{background:#fff;color:#102a43;border:1px solid #cbd5e1}.card{background:#fff;border:1px solid #dde6ed;border-radius:14px;padding:18px;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.formgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.wide{grid-column:1/-1}.field label{display:block;font-size:12px;font-weight:800;color:#52677a;margin-bottom:5px;text-transform:uppercase}.field input,.field select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px}.muted{color:#64748b;font-size:13px}.alert{padding:12px 14px;border-radius:9px;margin-bottom:14px}.success{background:#dcfce7;color:#166534}.error{background:#fee2e2;color:#991b1b}.hallhead{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.inline{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.inline input,.inline select{padding:7px;border:1px solid #cbd5e1;border-radius:7px;max-width:150px}.seatgrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:10px;margin-top:14px}.seat{border:1px solid #e2e8f0;border-radius:11px;padding:11px;background:#f8fafc}.badge{display:inline-block;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:800;background:#dcfce7;color:#166534}.badge.off{background:#fee2e2;color:#991b1b}.danger-note{font-size:12px;color:#9a3412;background:#fff7ed;padding:9px;border-radius:8px;margin-top:8px}@media(max-width:760px){.grid,.formgrid{grid-template-columns:1fr}.wide{grid-column:auto}.top{flex-direction:column}}</style>
</head>
<body><div class="wrap">
<div class="top"><div><h1 style="margin:0">Hall & Seat Tools</h1><div class="muted">Add/edit halls, bulk-create seat numbers, edit individual seats, disable or safely delete unused records.</div></div><div class="actions"><a class="btn light" href="{{ route('admin.study-space.index') }}">Study Space</a><a class="btn" href="{{ route('admin.dashboard') }}">Dashboard</a></div></div>
@if(session('success'))<div class="alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert error"><strong>Please correct:</strong> {{ $errors->first() }}</div>@endif
<div class="grid">
<div class="card"><h2>Add Study Hall</h2><form method="POST" action="{{ route('admin.study-space.halls.store') }}">@csrf<div class="formgrid"><div class="field"><label>Branch</label><select name="branch_id" required>@foreach($branches as $b)<option value="{{ $b->id }}">{{ $b->name }}</option>@endforeach</select></div><div class="field"><label>Hall Name</label><input name="name" required placeholder="Hall 1"></div><div class="field"><label>Floor</label><input name="floor" placeholder="Ground Floor"></div><div class="field"><label>Capacity</label><input type="number" min="1" max="1000" name="total_seats" required value="20"></div></div><label><input type="checkbox" name="status" value="1" checked> Active</label><div style="margin-top:12px"><button class="btn green">Create Hall</button></div></form></div>
<div class="card"><h2>Bulk Add Seats</h2><form method="POST" action="{{ route('admin.study-space.seats.bulk') }}">@csrf<div class="formgrid"><div class="field wide"><label>Study Hall</label><select name="study_hall_id" required>@foreach($halls as $h)<option value="{{ $h->id }}">{{ $h->branch?->name }} · {{ $h->name }} · {{ $h->seats_count }}/{{ $h->total_seats }}</option>@endforeach</select></div><div class="field"><label>Prefix</label><input name="prefix" placeholder="H1-"></div><div class="field"><label>Start No.</label><input type="number" min="1" name="start_no" value="1" required></div><div class="field"><label>Count</label><input type="number" min="1" max="500" name="count" value="20" required></div><div class="field"><label>Padding</label><select name="padding"><option value="2">2 → 01</option><option value="3">3 → 001</option><option value="1">1 → 1</option><option value="4">4 → 0001</option></select></div><div class="field wide"><label>Seat Type</label><select name="seat_type" required><option value="regular">Regular</option><option value="premium">Premium</option><option value="cabin">Cabin</option></select></div></div><div class="danger-note">Example: Prefix H1-, Start 1, Count 32, Padding 2 creates H1-01 through H1-32. If any duplicate exists, the full batch is stopped.</div><div style="margin-top:12px"><button class="btn green">Generate Seats</button></div></form></div>
</div>
@forelse($halls as $hall)
<div class="card"><div class="hallhead"><div><h2 style="margin:0 0 5px">{{ $hall->name }}</h2><div class="muted">{{ $hall->branch?->name }} · {{ $hall->floor ?: 'No floor set' }} · Actual seats {{ $hall->seats_count }} / Capacity {{ $hall->total_seats }}</div></div><div class="actions"><form class="inline" method="POST" action="{{ route('admin.study-space.halls.update',$hall) }}">@csrf @method('PATCH')<input name="name" value="{{ $hall->name }}" required><input name="floor" value="{{ $hall->floor }}" placeholder="Floor"><input type="number" min="1" max="1000" name="total_seats" value="{{ $hall->total_seats }}" required><label><input type="checkbox" name="status" value="1" @checked($hall->status)> Active</label><button class="btn">Save Hall</button></form><form method="POST" action="{{ route('admin.study-space.halls.destroy',$hall) }}" onsubmit="return confirm('Delete this hall? It can only be deleted when no seat records exist.')">@csrf @method('DELETE')<button class="btn red">Delete Hall</button></form></div></div>
<div class="seatgrid">@forelse($hall->seats as $seat)<div class="seat"><div class="inline" style="justify-content:space-between"><strong>{{ $seat->seat_no }}</strong><span class="badge {{ $seat->status?'':'off' }}">{{ $seat->status?'Active':'Disabled' }}</span></div><div class="muted">{{ ucfirst($seat->seat_type ?: 'regular') }} · Allocations: {{ $seat->allocations_count }}</div><form style="margin-top:9px" method="POST" action="{{ route('admin.study-space.seats.update',$seat) }}">@csrf @method('PATCH')<div class="formgrid"><div class="field"><label>Seat No.</label><input name="seat_no" value="{{ $seat->seat_no }}" required></div><div class="field"><label>Type</label><select name="seat_type" required><option value="regular" @selected($seat->seat_type==='regular')>Regular</option><option value="premium" @selected($seat->seat_type==='premium')>Premium</option><option value="cabin" @selected($seat->seat_type==='cabin')>Cabin</option></select></div></div><label><input type="checkbox" name="status" value="1" @checked($seat->status)> Available</label><div style="margin-top:8px"><button class="btn">Save Seat</button></div></form>@if($seat->allocations_count===0)<form style="margin-top:8px" method="POST" action="{{ route('admin.study-space.seats.destroy',$seat) }}" onsubmit="return confirm('Delete seat {{ $seat->seat_no }}?')">@csrf @method('DELETE')<button class="btn red">Delete Seat</button></form>@else<div class="danger-note">Allocation history exists, so this seat is protected from deletion. Disable it instead.</div>@endif</div>@empty<div class="muted">No individual seats added yet.</div>@endforelse</div>
</div>
@empty<div class="card muted">No study halls configured.</div>@endforelse
</div></body></html>
