<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Branch Management | C-Net Library</title>
<style>*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:#f3f6f8;color:#172033}.wrap{max-width:1450px;margin:28px auto;padding:0 18px}.top{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.btn{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:9px;padding:9px 13px;background:#102a43;color:#fff;text-decoration:none;font-weight:750;cursor:pointer}.card{background:#fff;border:1px solid #dfe7ed;border-radius:14px;padding:18px;box-shadow:0 5px 18px rgba(15,23,42,.04);margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.formgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.field label{display:block;font-size:12px;font-weight:800;color:#52677a;margin-bottom:5px}.field input,.field textarea,.field select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.full{grid-column:1/-1}.muted{color:#64748b;font-size:13px}.success,.error{padding:12px 14px;border-radius:10px;margin-bottom:14px}.success{background:#ecfdf5;border:1px solid #86efac}.error{background:#fef2f2;border:1px solid #fca5a5}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}th{color:#52677a;background:#f8fafc}.badge{display:inline-block;padding:4px 8px;border-radius:999px;background:#ecfdf5;color:#047857;font-weight:800;font-size:11px}.badge.off{background:#f1f5f9;color:#64748b}.inline{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:8px}.stat{background:#f8fafc;border-radius:8px;padding:8px}.stat strong{display:block;font-size:16px}@media(max-width:900px){.grid,.formgrid{grid-template-columns:1fr}.summary{grid-template-columns:1fr 1fr}.top{flex-direction:column}}</style></head><body><div class="wrap">
<div class="top"><div><h1 style="margin:0">Branch Management</h1><div class="muted">Create and manage multiple C-Net Library branches. Each branch can have its own halls, seats, slots, plans, lockers, students and staff.</div></div><a class="btn" href="{{ route('admin.dashboard') }}">Dashboard</a></div>
@if(session('success'))<div class="success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="error"><strong>Please correct:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid"><div class="card"><h2 style="margin-top:0">Add New Branch</h2><form method="POST" action="{{ route('admin.branches.store') }}">@csrf<div class="formgrid">
<div class="field"><label>Branch Name</label><input name="name" value="{{ old('name') }}" placeholder="C-Net Library - Sohsarai Branch" required></div>
<div class="field"><label>Branch Code</label><input name="code" value="{{ old('code') }}" placeholder="SOH-01" required></div>
<div class="field"><label>Mobile</label><input name="mobile" value="{{ old('mobile') }}"></div>
<div class="field"><label>Email</label><input type="email" name="email" value="{{ old('email') }}"></div>
<div class="field"><label>City</label><input name="city" value="{{ old('city') }}"></div>
<div class="field"><label>State</label><input name="state" value="{{ old('state','Bihar') }}"></div>
<div class="field full"><label>Address</label><textarea name="address" rows="2">{{ old('address') }}</textarea></div>
<div class="field"><label>Opening Time</label><input type="time" name="opening_time" value="{{ old('opening_time') }}"></div>
<div class="field"><label>Closing Time</label><input type="time" name="closing_time" value="{{ old('closing_time') }}"></div>
<div class="field"><label><input type="checkbox" name="is_24x7" value="1" style="width:auto" @checked(old('is_24x7'))> 24×7 Branch</label></div>
<div class="field"><label><input type="checkbox" name="status" value="1" style="width:auto" checked> Active</label></div>
</div><button class="btn" type="submit">Create Branch</button></form></div>
<div class="card"><h2 style="margin-top:0">How Multi-Branch Works</h2><p class="muted">After creating a branch, go to <strong>Study Hall & Seats</strong> and configure that branch's hall, seats, study slots and fee plans. Then go to <strong>Lockers</strong> to create branch-specific lockers. Admissions, students, attendance, finance and staff records remain branch-scoped.</p><p class="muted">Only Global/Super Admin can create or edit branches. For an existing branch with historical records, use <strong>Disabled</strong> instead of deleting it so financial and student history stays safe.</p></div></div>
<div class="card"><h2>Existing Branches</h2><div class="tablewrap"><table><thead><tr><th>Branch</th><th>Contact / Address</th><th>Timing</th><th>Operational Data</th><th>Status</th><th>Edit</th></tr></thead><tbody>@forelse($branches as $branch)<tr>
<td><strong>{{ $branch->name }}</strong><div class="muted">Code: {{ $branch->code }}</div></td>
<td>{{ $branch->mobile ?: '—' }}<br>{{ $branch->email ?: '' }}<div class="muted">{{ $branch->address }} {{ $branch->city }} {{ $branch->state }}</div></td>
<td>@if($branch->is_24x7)<strong>24×7</strong>@else{{ $branch->opening_time ?: '—' }} – {{ $branch->closing_time ?: '—' }}@endif</td>
<td><div class="summary"><div class="stat"><span class="muted">Students</span><strong>{{ $branch->students_count }}</strong></div><div class="stat"><span class="muted">Halls</span><strong>{{ $branch->study_halls_count }}</strong></div><div class="stat"><span class="muted">Slots</span><strong>{{ $branch->study_slots_count }}</strong></div><div class="stat"><span class="muted">Plans</span><strong>{{ $branch->fee_plans_count }}</strong></div></div></td>
<td><span class="badge {{ $branch->status?'':'off' }}">{{ $branch->status?'Active':'Disabled' }}</span></td>
<td><details><summary style="cursor:pointer;font-weight:800">Edit Branch</summary><form method="POST" action="{{ route('admin.branches.update',$branch) }}" style="margin-top:10px;min-width:300px">@csrf @method('PATCH')<div class="formgrid"><div class="field"><label>Name</label><input name="name" value="{{ $branch->name }}" required></div><div class="field"><label>Code</label><input name="code" value="{{ $branch->code }}" required></div><div class="field"><label>Mobile</label><input name="mobile" value="{{ $branch->mobile }}"></div><div class="field"><label>Email</label><input type="email" name="email" value="{{ $branch->email }}"></div><div class="field"><label>City</label><input name="city" value="{{ $branch->city }}"></div><div class="field"><label>State</label><input name="state" value="{{ $branch->state }}"></div><div class="field full"><label>Address</label><textarea name="address">{{ $branch->address }}</textarea></div><div class="field"><label>Opening</label><input type="time" name="opening_time" value="{{ $branch->opening_time }}"></div><div class="field"><label>Closing</label><input type="time" name="closing_time" value="{{ $branch->closing_time }}"></div><div class="field"><label><input type="checkbox" style="width:auto" name="is_24x7" value="1" @checked($branch->is_24x7)> 24×7</label></div><div class="field"><label>Status</label><select name="status"><option value="1" @selected($branch->status)>Active</option><option value="0" @selected(!$branch->status)>Disabled</option></select></div></div><button class="btn" type="submit">Save Changes</button></form></details></td>
</tr>@empty<tr><td colspan="6">No branches found.</td></tr>@endforelse</tbody></table></div></div>
</div></body></html>