<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\CommunicationLog;use App\Models\CommunicationTemplate;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Validation\Rule;use Illuminate\View\View;
class CommunicationController extends Controller{
public function index(Request $r):View{$templates=CommunicationTemplate::query()->withCount('logs')->latest()->get();$logs=CommunicationLog::query()->with(['student','enquiry','template','creator'])->when(!$r->user()->isGlobalAdmin(),fn($q)=>$q->where('branch_id',$r->user()->branch_id))->when($r->filled('channel'),fn($q)=>$q->where('channel',$r->string('channel')))->when($r->filled('status'),fn($q)=>$q->where('status',$r->string('status')))->latest()->paginate(30)->withQueryString();return view('admin.communications.index',compact('templates','logs'));}
private function data(Request $r,?CommunicationTemplate $t=null):array{$d=$r->validate(['name'=>['required','string','max:150'],'slug'=>['required','alpha_dash','max:150',Rule::unique('communication_templates','slug')->ignore($t?->id)],'channel'=>['required','in:email,sms,whatsapp'],'subject'=>['nullable','string','max:255'],'body'=>['required','string'],'status'=>['nullable','boolean']]);$d['status']=$r->boolean('status');return $d;}
public function store(Request $r):RedirectResponse{CommunicationTemplate::create($this->data($r));return back()->with('success','Communication template created.');}
public function update(Request $r,CommunicationTemplate $template):RedirectResponse{$template->update($this->data($r,$template));return back()->with('success','Communication template updated.');}
public function destroy(CommunicationTemplate $template):RedirectResponse{if($template->logs()->exists()){ $template->update(['status'=>false]);return back()->withErrors(['template'=>'Template has communication history, so it was disabled instead of permanently deleted.']);}$template->delete();return back()->with('success','Unused communication template deleted.');}
}
