<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Branch;
use App\Models\FeePlan;
use App\Models\Seat;
use App\Models\SeatAllocation;
use App\Models\Student;
use App\Models\StudyHall;
use App\Models\StudySlot;
use App\Support\AdminBranchScope;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\View\View;

class StudySpaceController extends Controller
{
    public function index(Request $request): View
    {
        $user=$request->user(); $branches=Branch::query()->where('status',true)->when(!$user->isGlobalAdmin(),fn($q)=>$q->whereKey($user->branch_id))->orderBy('name')->get(); $branchIds=$branches->pluck('id');
        $halls=StudyHall::query()->whereIn('branch_id',$branchIds)->withCount('seats')->with(['seats'=>fn($q)=>$q->withCount('allocations')->orderBy('seat_no')])->orderBy('branch_id')->orderBy('name')->get();
        $slots=StudySlot::query()->whereIn('branch_id',$branchIds)->orderBy('branch_id')->orderBy('duration_hours')->orderBy('start_time')->get(); $plans=FeePlan::query()->whereIn('branch_id',$branchIds)->with('studySlot')->orderBy('branch_id')->orderBy('monthly_fee')->get();
        $students=Student::query()->whereIn('branch_id',$branchIds)->where('status','active')->orderBy('name')->get(['id','branch_id','student_code','name','mobile']);
        $allocations=SeatAllocation::query()->whereHas('student',fn($q)=>$q->whereIn('branch_id',$branchIds))->with(['student:id,branch_id,student_code,name,mobile','seat.studyHall:id,branch_id,name','studySlot:id,branch_id,name,start_time,end_time,duration_hours'])->latest('allocated_from')->latest('id')->paginate(30)->withQueryString();
        $summary=['halls'=>$halls->count(),'seats'=>$halls->sum('seats_count'),'slots'=>$slots->where('status',true)->count(),'active_allocations'=>SeatAllocation::query()->whereHas('student',fn($q)=>$q->whereIn('branch_id',$branchIds))->whereIn('status',['active','reserved'])->whereDate('allocated_from','<=',today())->where(fn($q)=>$q->whereNull('allocated_to')->orWhereDate('allocated_to','>=',today()))->count()];
        return view('admin.study-space.index',compact('branches','halls','slots','plans','students','allocations','summary'));
    }

    public function seatTools(Request $request): View
    {
        $user=$request->user();
        $branches=Branch::query()->where('status',true)->when(!$user->isGlobalAdmin(),fn($q)=>$q->whereKey($user->branch_id))->orderBy('name')->get();
        $allowedIds=$branches->pluck('id');
        $selectedBranchId=$request->integer('branch_id') ?: null;
        if(!$user->isGlobalAdmin()) $selectedBranchId=(int)$user->branch_id;
        if($selectedBranchId && !$allowedIds->contains($selectedBranchId)) abort(403,'You cannot manage this branch.');
        $hallBranchIds=$selectedBranchId ? collect([$selectedBranchId]) : $allowedIds;
        $halls=StudyHall::query()->whereIn('branch_id',$hallBranchIds)->withCount('seats')->with(['branch','seats'=>fn($q)=>$q->withCount('allocations')->orderBy('seat_no')])->orderBy('branch_id')->orderBy('name')->get();
        $selectedBranch=$selectedBranchId ? $branches->firstWhere('id',$selectedBranchId) : null;
        return view('admin.study-space.seat-tools',compact('branches','halls','selectedBranchId','selectedBranch'));
    }

    public function storeHall(Request $r):RedirectResponse{$d=$r->validate(['branch_id'=>['required','exists:branches,id'],'name'=>['required','string','max:120'],'floor'=>['nullable','string','max:80'],'total_seats'=>['required','integer','min:1','max:1000'],'status'=>['nullable','boolean']]);AdminBranchScope::authorize($r,(int)$d['branch_id']);$d['status']=$r->boolean('status',true);StudyHall::create($d);return back()->with('success','Study hall created successfully. Add individual seat numbers below.');}
    public function updateHall(Request $r,StudyHall $hall):RedirectResponse{AdminBranchScope::authorize($r,$hall->branch_id);$d=$r->validate(['name'=>['required','string','max:120'],'floor'=>['nullable','string','max:80'],'total_seats'=>['required','integer','min:1','max:1000'],'status'=>['nullable','boolean']]);$d['status']=$r->boolean('status');$hall->update($d);return back()->with('success','Study hall updated. Capacity is descriptive; actual seats are controlled by individual seat records.');}
    public function destroyHall(Request $r,StudyHall $hall):RedirectResponse{AdminBranchScope::authorize($r,$hall->branch_id);if($hall->seats()->exists())return back()->withErrors(['hall'=>'Hall cannot be deleted while seat records exist. Delete unused seats first, or disable the hall to preserve allocation history.']);$n=$hall->name;$hall->delete();return back()->with('success',"Study hall {$n} deleted.");}
    public function storeSeat(Request $r):RedirectResponse{$d=$r->validate(['study_hall_id'=>['required','exists:study_halls,id'],'seat_no'=>['required','string','max:40'],'seat_type'=>['required',Rule::in(['regular','premium','cabin'])],'status'=>['nullable','boolean']]);$h=StudyHall::findOrFail($d['study_hall_id']);AdminBranchScope::authorize($r,$h->branch_id);$r->validate(['seat_no'=>[Rule::unique('seats')->where(fn($q)=>$q->where('study_hall_id',$h->id))]]);$d['status']=$r->boolean('status',true);Seat::create($d);return back()->with('success','Seat added successfully.');}
    public function bulkStoreSeats(Request $r):RedirectResponse{$d=$r->validate(['study_hall_id'=>['required','exists:study_halls,id'],'prefix'=>['nullable','string','max:20','regex:/^[A-Za-z0-9_-]*$/'],'start_no'=>['required','integer','min:1','max:9999'],'count'=>['required','integer','min:1','max:500'],'padding'=>['required','integer','min:1','max:4'],'seat_type'=>['required',Rule::in(['regular','premium','cabin'])]]);$h=StudyHall::findOrFail($d['study_hall_id']);AdminBranchScope::authorize($r,$h->branch_id);$prefix=$d['prefix']??'';$numbers=[];for($i=0;$i<(int)$d['count'];$i++)$numbers[]=$prefix.str_pad((string)((int)$d['start_no']+$i),(int)$d['padding'],'0',STR_PAD_LEFT);$existing=Seat::query()->where('study_hall_id',$h->id)->whereIn('seat_no',$numbers)->pluck('seat_no')->all();if($existing)return back()->withErrors(['bulk_seats'=>'Bulk generation stopped. These seat numbers already exist: '.implode(', ',array_slice($existing,0,12)).(count($existing)>12?' ...':'')])->withInput();DB::transaction(function()use($h,$numbers,$d){foreach($numbers as $no)Seat::create(['study_hall_id'=>$h->id,'seat_no'=>$no,'seat_type'=>$d['seat_type'],'status'=>true]);});return back()->with('success',count($numbers).' seats created for '.$h->name.'.');}
    public function updateSeat(Request $r,Seat $seat):RedirectResponse{$seat->loadMissing('studyHall');AdminBranchScope::authorize($r,$seat->studyHall->branch_id);$d=$r->validate(['seat_no'=>['required','string','max:40',Rule::unique('seats')->where(fn($q)=>$q->where('study_hall_id',$seat->study_hall_id))->ignore($seat->id)],'seat_type'=>['required',Rule::in(['regular','premium','cabin'])],'status'=>['nullable','boolean']]);$d['status']=$r->boolean('status');$seat->update($d);return back()->with('success','Seat updated.');}
    public function destroySeat(Request $r,Seat $seat):RedirectResponse{$seat->loadMissing('studyHall');AdminBranchScope::authorize($r,$seat->studyHall->branch_id);if($seat->allocations()->exists())return back()->withErrors(['seat'=>'Seat '.$seat->seat_no.' has allocation history and cannot be deleted. Disable it instead so historical records remain safe.']);$n=$seat->seat_no;$seat->delete();return back()->with('success',"Seat {$n} deleted successfully.");}
    public function storeSlot(Request $r):RedirectResponse{$d=$r->validate(['branch_id'=>['required','exists:branches,id'],'name'=>['required','string','max:120'],'duration_hours'=>['required','integer','min:1','max:24'],'start_time'=>['nullable','date_format:H:i'],'end_time'=>['nullable','date_format:H:i'],'is_24x7'=>['nullable','boolean'],'is_flexible'=>['nullable','boolean'],'status'=>['nullable','boolean']]);AdminBranchScope::authorize($r,(int)$d['branch_id']);$d['is_24x7']=$r->boolean('is_24x7');$d['is_flexible']=$r->boolean('is_flexible');$d['status']=$r->boolean('status',true);StudySlot::create($d);return back()->with('success','Study slot created successfully.');}
    public function updateSlot(Request $r,StudySlot $slot):RedirectResponse{AdminBranchScope::authorize($r,$slot->branch_id);$d=$r->validate(['name'=>['required','string','max:120'],'duration_hours'=>['required','integer','min:1','max:24'],'start_time'=>['nullable','date_format:H:i'],'end_time'=>['nullable','date_format:H:i'],'is_24x7'=>['nullable','boolean'],'is_flexible'=>['nullable','boolean'],'status'=>['nullable','boolean']]);$d['is_24x7']=$r->boolean('is_24x7');$d['is_flexible']=$r->boolean('is_flexible');$d['status']=$r->boolean('status');$slot->update($d);return back()->with('success','Study slot updated.');}
    public function storePlan(Request $r):RedirectResponse{$d=$r->validate(['branch_id'=>['required','exists:branches,id'],'study_slot_id'=>['required','exists:study_slots,id'],'name'=>['required','string','max:120'],'monthly_fee'=>['required','numeric','min:0'],'quarterly_fee'=>['nullable','numeric','min:0'],'half_yearly_fee'=>['nullable','numeric','min:0'],'yearly_fee'=>['nullable','numeric','min:0'],'admission_fee'=>['nullable','numeric','min:0'],'registration_fee'=>['nullable','numeric','min:0'],'security_deposit'=>['nullable','numeric','min:0'],'late_fee'=>['nullable','numeric','min:0'],'validity_days'=>['required','integer','min:1','max:3660'],'status'=>['nullable','boolean']]);AdminBranchScope::authorize($r,(int)$d['branch_id']);$s=StudySlot::findOrFail($d['study_slot_id']);abort_unless((int)$s->branch_id===(int)$d['branch_id'],422,'Study slot does not belong to selected branch.');$d['status']=$r->boolean('status',true);FeePlan::create($d);return back()->with('success','Fee plan created successfully.');}
    public function updatePlan(Request $r,FeePlan $plan):RedirectResponse{AdminBranchScope::authorize($r,$plan->branch_id);$d=$r->validate(['study_slot_id'=>['required','exists:study_slots,id'],'name'=>['required','string','max:120'],'monthly_fee'=>['required','numeric','min:0'],'quarterly_fee'=>['nullable','numeric','min:0'],'half_yearly_fee'=>['nullable','numeric','min:0'],'yearly_fee'=>['nullable','numeric','min:0'],'admission_fee'=>['nullable','numeric','min:0'],'registration_fee'=>['nullable','numeric','min:0'],'security_deposit'=>['nullable','numeric','min:0'],'late_fee'=>['nullable','numeric','min:0'],'validity_days'=>['required','integer','min:1','max:3660'],'status'=>['nullable','boolean']]);$s=StudySlot::findOrFail($d['study_slot_id']);abort_unless((int)$s->branch_id===(int)$plan->branch_id,422,'Study slot does not belong to plan branch.');$d['status']=$r->boolean('status');$plan->update($d);return back()->with('success','Fee plan updated.');}
    public function allocate(Request $r):RedirectResponse{$d=$r->validate(['student_id'=>['required','exists:students,id'],'seat_id'=>['required','exists:seats,id'],'study_slot_id'=>['required','exists:study_slots,id'],'allocated_from'=>['required','date'],'allocated_to'=>['nullable','date','after_or_equal:allocated_from'],'status'=>['required',Rule::in(['reserved','active'])],'remarks'=>['nullable','string','max:500']]);$student=Student::findOrFail($d['student_id']);$seat=Seat::with('studyHall')->findOrFail($d['seat_id']);$slot=StudySlot::findOrFail($d['study_slot_id']);AdminBranchScope::authorize($r,$student->branch_id);abort_unless((int)$seat->studyHall->branch_id===(int)$student->branch_id,422,'Seat is in another branch.');abort_unless((int)$slot->branch_id===(int)$student->branch_id,422,'Study slot is in another branch.');$to=$d['allocated_to']??$d['allocated_from'];$conflict=SeatAllocation::query()->where('seat_id',$seat->id)->whereIn('status',['reserved','active'])->whereDate('allocated_from','<=',$to)->where(fn($q)=>$q->whereNull('allocated_to')->orWhereDate('allocated_to','>=',$d['allocated_from']))->when($slot->start_time&&$slot->end_time,function($q)use($slot){$q->where(function($time)use($slot){$time->whereNull('start_time')->orWhereNull('end_time')->orWhere(fn($o)=>$o->where('start_time','<',$slot->end_time)->where('end_time','>',$slot->start_time));});})->exists();if($conflict)return back()->withErrors(['seat_id'=>'Selected seat is already allocated for an overlapping period/slot.'])->withInput();$m=$student->memberships()->where('study_slot_id',$slot->id)->whereIn('status',['active','pending'])->latest('id')->first();SeatAllocation::create(['student_id'=>$student->id,'student_membership_id'=>$m?->id,'seat_id'=>$seat->id,'study_slot_id'=>$slot->id,'allocated_from'=>$d['allocated_from'],'allocated_to'=>$d['allocated_to']??null,'start_time'=>$slot->start_time,'end_time'=>$slot->end_time,'status'=>$d['status'],'remarks'=>$d['remarks']??null]);return back()->with('success','Seat allocated successfully.');}
    public function updateAllocation(Request $r,SeatAllocation $allocation):RedirectResponse{$allocation->loadMissing('student');AdminBranchScope::authorize($r,$allocation->student->branch_id);$d=$r->validate(['status'=>['required',Rule::in(['reserved','active','completed','cancelled'])],'allocated_to'=>['nullable','date','after_or_equal:'.$allocation->allocated_from->toDateString()],'remarks'=>['nullable','string','max:500']]);$allocation->update($d);return back()->with('success','Seat allocation updated.');}
}
